# Generated by Django 3.2.15 on 2023-06-13 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('name', models.CharField(max_length=255, verbose_name='品牌名称')),
                ('mini_sources', models.IntegerField(default=10, verbose_name='爬虫sources')),
                ('mini_count', models.IntegerField(default=10, verbose_name='爬虫产品数量')),
                ('filter_sources', models.IntegerField(default=10, verbose_name='筛选sources')),
                ('filter_count', models.IntegerField(default=10, verbose_name='筛选产品数量')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ECGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('part', models.CharField(blank=True, default='', max_length=255, verbose_name='零件号')),
                ('mfr_part_no', models.CharField(blank=True, default='', max_length=255, verbose_name='制造商零件号')),
                ('vendor_part_no', models.CharField(blank=True, default='', max_length=255, verbose_name='供应商零件号')),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='制造商建议零售价')),
                ('federal_govt_spa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='联邦政府价格')),
                ('ingram_micro_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='英迈国际价格')),
                ('ec_status', models.BooleanField(null=True, verbose_name='EC爬取状态')),
                ('inm_status', models.BooleanField(null=True, verbose_name='inm爬取状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GSAGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('brand_name', models.CharField(max_length=255, verbose_name='品牌名称')),
                ('sin', models.CharField(default='', max_length=255, verbose_name='sin')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='产品名称')),
                ('product_description', models.CharField(blank=True, default='', max_length=255, verbose_name='产品描述')),
                ('product_description2_strong', models.CharField(blank=True, default='', max_length=255, verbose_name='产品描述strong')),
                ('product_description2', models.CharField(blank=True, default='', max_length=255, verbose_name='产品描述2')),
                ('gsa_advantage_price_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格1')),
                ('gsa_advantage_price_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格2')),
                ('gsa_advantage_price_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格3')),
                ('coo', models.CharField(blank=True, default='', max_length=255, verbose_name='原产地')),
                ('mfr_part_no_gsa', models.CharField(blank=True, default='', max_length=255, verbose_name='制造商零件号')),
                ('gsa_status', models.BooleanField(null=True, verbose_name='GSA爬取状态')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='url')),
                ('source', models.IntegerField(verbose_name='source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
