# Generated by Django 3.2.15 on 2023-05-21 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('part', models.CharField(blank=True, default='', max_length=255, verbose_name='零件号')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255, verbose_name='制造商')),
                ('manufacturer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='制造商名称')),
                ('mfr_part_no', models.CharField(blank=True, default='', max_length=255, verbose_name='制造商零件号')),
                ('vendor_part_no', models.CharField(blank=True, default='', max_length=255, verbose_name='供应商零件号')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='产品名称')),
                ('product_description', models.CharField(blank=True, default='', max_length=255, verbose_name='产品描述')),
                ('uoi', models.CharField(blank=True, default='EA', max_length=255, verbose_name='发货单位')),
                ('commercial_price_list', models.CharField(blank=True, default='', max_length=255, verbose_name='商业价格表')),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='制造商建议零售价')),
                ('federal_govt_spa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='联邦政府价格')),
                ('ingram_micro_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='英迈国际价格')),
                ('gsa_advantage_price_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格1')),
                ('gsa_advantage_price_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格2')),
                ('gsa_advantage_price_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格3')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
