# Generated by Django 3.2.15 on 2023-06-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgood',
            name='part',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='零件号'),
        ),
    ]
