# Generated by Django 3.2.15 on 2023-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsagood',
            name='url',
            field=models.CharField(max_length=255, verbose_name='url'),
        ),
    ]
