# Generated by Django 3.2.15 on 2023-06-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_gsagood_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='keys',
            field=models.CharField(default='', max_length=255, verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='gsagood',
            name='manufacturer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='制造商名称'),
        ),
    ]
