# Generated by Django 3.2.15 on 2023-06-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_ecgood_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgood',
            name='ec_status',
            field=models.BooleanField(default=False, null=True, verbose_name='EC爬取状态'),
        ),
        migrations.AlterField(
            model_name='ecgood',
            name='inm_status',
            field=models.BooleanField(default=False, null=True, verbose_name='inm爬取状态'),
        ),
        migrations.AlterField(
            model_name='gsagood',
            name='gsa_status',
            field=models.BooleanField(default=False, null=True, verbose_name='GSA爬取状态'),
        ),
    ]
