# Generated by Django 3.2.15 on 2023-06-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_gsagood_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsagood',
            name='product_description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='gsagood',
            name='product_description2_strong',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='产品描述strong'),
        ),
    ]
