# Generated by Django 3.2.15 on 2023-06-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20230619_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsagood',
            name='product_description2',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='产品描述2'),
        ),
        migrations.AlterField(
            model_name='gsagood',
            name='product_description2_strong',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='产品描述strong'),
        ),
    ]
