# Generated by Django 3.2.15 on 2023-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20230605_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsagood',
            name='product_description2_strong',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='产品描述strong'),
        ),
    ]
