# Generated by Django 3.2.15 on 2023-07-31 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20230619_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSAGood500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('key', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='url')),
                ('source', models.IntegerField(verbose_name='source')),
                ('gsa_status', models.BooleanField(null=True, verbose_name='GSA爬取状态')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
