# Generated by Django 3.2.15 on 2023-10-08 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_orderfilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFilledStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('mfr_part_number', models.CharField(default='', max_length=255, verbose_name='零件号')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('extended_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总价')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('contractor_name', models.CharField(default='', max_length=255, verbose_name='承包商名称')),
                ('contract_number', models.CharField(default='', max_length=255, verbose_name='合同编号')),
                ('mfr_part_number', models.CharField(default='', max_length=255, verbose_name='零件号')),
                ('item_name', models.CharField(default='', max_length=255, verbose_name='物品名称')),
                ('mfr_name', models.CharField(default='', max_length=255, verbose_name='制造商名称')),
                ('extended_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总价')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
