# Generated by Django 3.2.15 on 2023-08-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_gsagood500_ec_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsagood500',
            name='source',
            field=models.IntegerField(default=0, verbose_name='source'),
        ),
    ]
