# Generated by Django 3.2.15 on 2023-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_gsagood500_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsagood500',
            name='mfr_part_no',
            field=models.CharField(default='', max_length=255, verbose_name='制造商零件号'),
        ),
    ]
