# Generated by Django 3.2.15 on 2023-08-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_gsagood500_mfr_part_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsagood500',
            name='gsa_advantage_price_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格1'),
        ),
        migrations.AddField(
            model_name='gsagood500',
            name='gsa_advantage_price_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格2'),
        ),
        migrations.AddField(
            model_name='gsagood500',
            name='gsa_advantage_price_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='GSA优势价格3'),
        ),
        migrations.AddField(
            model_name='gsagood500',
            name='gsa_price_status',
            field=models.BooleanField(null=True, verbose_name='GSA价格爬取状态'),
        ),
    ]
